'use client'
import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import Footer from "./_components/Footer";
import 'bootstrap/dist/css/bootstrap.min.css';
import $ from 'jquery';
import { useState } from "react";
import '@fortawesome/fontawesome-free/css/all.min.css'; 
import { CartContext } from "./_context/CartContext";

const inter = Roboto({ subsets: ["latin"],
weight:'700' });

// export const metadata = {
//   title: "RodiRayDan",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [cart, setCart] = useState([]);
  return (
    <CartContext.Provider value={{ cart, setCart }}>
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
         {/* Include the jQuery script */}
         <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
      </body>
    </html>
    </CartContext.Provider>
  );
}
